name: deploy-orders

on:
  pull_request:
    paths:
      - 'orders/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.285.0
      - run: cd orders && npm install
